### ISSUE TITLE
日志信息输出

### ISSUE THREAD

**Issue by fawdlstty** [xmh0511/xfinal#1]
也许可以提供一种on_log方法，提供日志回调函数，便于日志记录
```cpp
http_server _server (1);
_server.on_log ([] (int _errno, const char *_msg) {
    //自己的日志信息存储方式，比如LOG_INFO...
});
```

**Comment by xmh0511** [comment]
日志记录 用户可以通过相关的库去使用呀 每个接口中记录信息 至于具体的信息怎么存储 是由日志库决定的 这里提供全局的on_log 出于什么考虑呢

**Comment by fawdlstty** [comment]
记录库的错误信息，比如
https://github.com/xmh0511/xfinal/blob/master/http_server.hpp#L81

**Comment by xmh0511** [comment]
好 这个我会加个统一处理的接口

**Comment by fawdlstty** [comment]
另外这个库是否考虑加上开源协议呢？

**Comment by xmh0511** [comment]
嗯  这块还没来得及做 你是否可以提个pr

**Comment by fawdlstty** [comment]
这个只有你来吧。毕竟是你的项目，看你想以怎样的方式开源咯。

**Comment by xmh0511** [comment]
server.on_error([](std::exception const& ec) {
      std::cout<<ec.what()<<std::endl;
});
已提供该接口
