### ISSUE TITLE
【提议】标准化方法名称

### ISSUE THREAD

**Issue by fawdlstty** [xmh0511/xfinal#10]
目前xfinal里有部分方法名称比较混乱。比如：param ()、raw_url_params ()、raw_key_params ()、url_params ()、key_params ()、query ()、url_form ()、multipart_form ()等，一方面部分接口含义不具标志性，比如HTTP协议中，URL格式是这样：
```
schema://host:port/path?query
```

问号之后的内容实际应该叫Query String，但query函数实际查的是POST传递的参数的结果；其次应该用param还是url_params、key_params，不看源码几乎无法用，凭感觉写也非常容易出错。建议标准化函数名，以提供更直观的接口名称。建议：

- .get_value (std::string _key)
    + 查询get参数，也就是URL中Query后接的键值对的解析
- .get_values ()
    + 获取所有get参数，也就是URL中Query后接的键值对集合
- post_value (std::string _key)
    + 查询port参数，也就是通过Http Content传递上来的键值对/json/Form的解析
- post_values ()
    + 获取所有port参数，也就是通过Http Content传递上来的键值对/json/Form的解析
- get_or_post_value (std::string _key)
    + 在get参数中找，如果不存在则在post参数中找
- query ()
    + 获取HTTP查询字符串，也就是问号后接的一串字符串

**Comment by xmh0511** [comment]
> 目前xfinal里有部分方法名称比较混乱。比如：param ()、raw_url_params ()、raw_key_params ()、url_params ()、key_params ()、query ()、url_form ()、multipart_form ()等，一方面部分接口含义不具标志性，比如HTTP协议中，URL格式是这样：
> 
> ```
> schema://host:port/path?query
> ```
> 
> 问号之后的内容实际应该叫Query String，但query函数实际查的是POST传递的参数的结果；其次应该用param还是url_params、key_params，不看源码几乎无法用，凭感觉写也非常容易出错。建议标准化函数名，以提供更直观的接口名称。建议：
> 
> * .get_value (std::string _key)
>   
>   * 查询get参数，也就是URL中Query后接的键值对的解析
> * .get_values ()
>   
>   * 获取所有get参数，也就是URL中Query后接的键值对集合
> * post_value (std::string _key)
>   
>   * 查询port参数，也就是通过Http Content传递上来的键值对/json/Form的解析
> * post_values ()
>   
>   * 获取所有port参数，也就是通过Http Content传递上来的键值对/json/Form的解析
> * get_or_post_value (std::string _key)
>   
>   * 在get参数中找，如果不存在则在post参数中找
> * query ()
>   
>   * 获取HTTP查询字符串，也就是问号后接的一串字符串

query()方法的命名是参照了一些java框架，raw_*这种形式的接口都是返回http明文中相应的原始字符串内容。key_params 和url_params分别对应不同的get中的url的值 `/key?abc=1&b=2` 或 `/path/1/2`

**Comment by fawdlstty** [comment]
raw可以去掉，实际业务中其实用不到；真需要原始内容的情况，通过form提交

**Comment by xmh0511** [comment]
> raw可以去掉，实际业务中其实用不到；真需要原始内容的情况，通过form提交

静态文件请求等应用场景需要用到

**Comment by fawdlstty** [comment]
特殊场合下非标准HTTP请求才需要用到；标准HTTP请求不需要考虑

**Comment by xmh0511** [comment]
fixed https://github.com/xmh0511/xfinal/tree/02145b3ad4ea925508f8eb642a04e6f374d8a1cb
