### ISSUE TITLE
【bug】res.write_file_view ()函数写入文件长度不正确

### ISSUE THREAD

**Issue by fawdlstty** [xmh0511/xfinal#11]
通过此函数写入长度950 KB (973,725 字节)大小的js文件，网页端实际下载到的文件大小为91.5 KB (93,712 字节)。示例代码：
```cpp
_s->set_not_found_callback ([] (xfinal::request &req, xfinal::response &res) {
	std::string _file = fmt::format ("./wwwroot{}", req.url ());
	if (fs::exists (_file)) {
		res.write_file_view (_file);
	} else {
		res.write_string ("404", false, xfinal::http_status::not_found);
	}
});
```

**Comment by fawdlstty** [comment]
出现异常的文件（需解压）：
[js.zip](https://github.com/xmh0511/xfinal/files/6436005/js.zip)

**Comment by xmh0511** [comment]
> 通过此函数写入长度950 KB (973,725 字节)大小的js文件，网页端实际下载到的文件大小为91.5 KB (93,712 字节)。示例代码：
> 
> ```c++
> _s->set_not_found_callback ([] (xfinal::request &req, xfinal::response &res) {
> 	std::string _file = fmt::format ("./wwwroot{}", req.url ());
> 	if (fs::exists (_file)) {
> 		res.write_file_view (_file);
> 	} else {
> 		res.write_string ("404", false, xfinal::http_status::not_found);
> 	}
> });
> ```

写文件不要用这个接口，这个接口是渲染模板的，其中如果文件中包含了渲染指令，那就会有特别处理
<img width="1078" alt="截屏2021-05-07 上午9 54 42" src="https://user-images.githubusercontent.com/17973891/117386907-52e9da00-af1a-11eb-8475-9db5f6263810.png">
<img width="1157" alt="截屏2021-05-07 上午9 54 57" src="https://user-images.githubusercontent.com/17973891/117386911-54b39d80-af1a-11eb-8013-0d7d44d2c7d8.png"> 

`#(`是模板指令

**Comment by fawdlstty** [comment]
res.write_file()接口有时候不会在网页上预览这个文件，而是把这个文件下载下来，我是希望这个js文件像正常的服务器端js一样使用

**Comment by xmh0511** [comment]
> res.write_file()接口有时候不会在网页上预览这个文件，而是把这个文件下载下来，我是希望这个js文件像正常的服务器端js一样使用

根据你请求的方式，如果你是直接默认浏览器地址请求那么根据content-type判断是下载还是显示内容这是浏览器行为，你可以通过设置content-type完成。在调用write_file之前，通过add_header("content-type","xxxx")完成

**Comment by xmh0511** [comment]
Using the interface in an incorrect way, I didn't see any issue here.
