### ISSUE TITLE
websocket，服务器端发送字节长度==126的情况

### ISSUE THREAD

**Issue by fawdlstty** [xmh0511/xfinal#2]
[if (message_size < 126) {](https://github.com/xmh0511/xfinal/blob/master/xfinal/xfinal/websokcet.hpp#L111)

[} else if (message_size > 126 ) {](https://github.com/xmh0511/xfinal/blob/master/xfinal/xfinal/websokcet.hpp#L122)

代码中貌似没判断待发送字节数==126的情况

**Comment by xmh0511** [comment]
已经修复，能否测试一下修复后的结果，即正好写入126字节看结果是否符合预期

**Comment by fawdlstty** [comment]
暂时不太方便，，我不运行xfinal代码，我只参考实现
