### ISSUE TITLE
【建议】使用submodule的方式，去除boost的依赖

### ISSUE THREAD

**Issue by fawdlstty** [xmh0511/xfinal#3]

**Comment by xmh0511** [comment]
已修改

**Comment by fawdlstty** [comment]
呃我是这个意思，想确认下能否做到这样：下载仓库并更新子模块后，引入xfinal文件就能用。以前是有boost引用，使得无法直接用，需要安装boost支持；现在版本代码包含`#include <asio.hpp>`，使得必须指定include才能使用

**Comment by xmh0511** [comment]
xfinal 本来就是脱离boost的，是asio only 的

**Comment by fawdlstty** [comment]
最新更新的版本代码包含#include <asio.hpp>，使得必须指定include路径才能使用；对于子模块来说，相对路径固定，可以改成相对路径引入asio的方式

**Comment by xmh0511** [comment]
我大概知道你得意思了

**Comment by xmh0511** [comment]
这样行不通，asio必须作为公共库引入，否则asio内部的路径都是错误的

**Comment by fawdlstty** [comment]
不使用子模块，然后修改asio内部的所有include呢？
