### ISSUE TITLE
【建议】新增对异步的支持

### ISSUE THREAD

**Issue by fawdlstty** [xmh0511/xfinal#4]
建议支持异步的方式，避免cpu的浪费。问题点在于，在router指定的webapi方法里，调用client传递请求交由其他服务端处理；在这个过程中，其他服务端的处理时长期间，webapi内部的线程是阻塞状态，这种请求多了之后，同时远程处理的线程数超过xfinal服务线程数，将较大程度影响xfinal的性能

**Comment by xmh0511** [comment]
client支持异步调用

**Comment by fawdlstty** [comment]
client的这种异步方式，对webapi方法不友好，不能把异步结果返回给webapi方法的调用者

**Comment by xmh0511** [comment]
@fawdlstty  已支持延迟回应
