### ISSUE TITLE
【建议】关于stop逻辑的处理

### ISSUE THREAD

**Issue by fawdlstty** [xmh0511/xfinal#9]
stop服务时，如果还存在已建立的ws链接，那么执行stop前，xfinal自动断开所有ws链接并调用on close回调。
此特性导致的问题：假如开发者在on open事件存储了xfinal::websocket的智能指针，on close事件清除，假如开发者没有在stop前手工清理所有链接，将导致程序崩溃。建议将此步骤转由xfinal自动处理。

**Comment by xmh0511** [comment]
这个目前还没有想到不影响stop执行时间的方法，需要进一步的考虑有没有优雅的实现方式

**Comment by xmh0511** [comment]
已修复
